version: "3.8"
services:
  api:
    build: "."
    command: "npm run start-dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV}


