version: "3.8"
services:
  api:
    image: node:16.14-alpine
    restart: always
    user: node
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run start-dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: ${NODE_ENV}
